name: omega_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3'

dependencies:
  dio: ^5.3.0
  email_validator: ^2.1.17
  flutter:
    sdk: flutter
  flutter_sticky_header: ^0.6.5
  flutter_svg: ^2.0.7
  google_fonts: ^4.0.4
  pixel_snap: ^0.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/background.png
    - assets/images/icon_google_color.svg
    - assets/images/icon_vk_color.svg
    - assets/images/icon_yandex_color.svg
    - assets/images/icon_yandex_color.png
    - assets/images/icon_vk_color.png
    - assets/images/logo.svg
    - assets/images/login.svg
    - assets/images/cart.svg
    - assets/images/favorite.svg
    - assets/images/footer_logo.png
    - assets/images/download.png
    - assets/images/social_vk.svg
    - assets/images/social_tg.svg
    - assets/images/social_yt.svg